# Generated by Django 3.0.5 on 2023-03-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimForm',
            new_name='ClaimFormModelForm',
        ),
    ]
