# Generated by Django 3.0.5 on 2023-03-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230324_0521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimFormModelForm',
            new_name='ClaimForm',
        ),
    ]
