from reportlab.pdfgen import canvas
from django.http import HttpResponse
from .models import Customer
from customer.models import Customer, ClaimForm
import csv


def generate_pdf(modeladmin, request, queryset):
    # Retrieve data from your database
    data = Customer.username()


    # Create a new PDF docume
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="cover_note.pdf"'
    pdf = canvas.Canvas(response)

    # Add content to the PDF document
    pdf.drawString(100, 750, "My Cover Note")
    pdf.drawString(100, 7.,.00, f"Generated by {request.user.username}")
    pdf.drawString(100, 650, "Data from MyModel:")

    y = 620
    for item in data:
        pdf.drawString(100, y, str(item))
        y -= 20

    # Save the PDF document and return the response
    pdf.save()
    return response


generate_pdf.short_description = "Generate PDF cover note"

def generate_report(modeladmin, request, queryset):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="my_report.csv"'

    writer = csv.writer(response)
    writer.writerow(['ID', 'username', 'address', 'mobile'])

    for obj in queryset:
        writer.writerow([obj.id, obj.username, obj.address, obj.mobile])

    return response


actions = [generate_report, generate_pdf]

